package-name: TSR.Fake.Direct.Specular
visual-name: TSR Fake Direct Specular
destination-folder: Assets/VRLabs/Toony Standard Rebuild Modules/TSR Fake Direct Specular
extra-generated-meta:
  - path: Assets/VRLabs
    guid: 652a1ba5b00554143bc9a76307dbc4e8
  - path: Assets/VRLabs/Toony Standard Rebuild Modules
    guid: d3d02b5b274410849ba3e6c360e2f005
  - path: Assets/VRLabs/Toony Standard Rebuild Modules/TSR Fake Direct Specular
    guid: 0a5f499e431766047a569198695ee805